### PR TITLE
Upgrade WordPress to 4.2

### PR DESCRIPTION
**Pull request by jamesgpearce**
Tested with 

hhvm perf.php --hhvm hhvm --repo-auth --i-am-not-benchmarking --wordpress

image

### CODE REVIEW

**Comment by rrh** [comment]
Rather than committing the wordpress .gz file into this github repository, is there any way that this can be downloaded as needed from an authoritative site? True, no other framework does this in the oss-performance world, yet.  However, doing the download when/if needed would save the git checkout time and bloat for all users of this repository.

**Comment by fredemmott** [comment]
We've tried that - it generally makes things unreliable and suddenly break.

**Comment by fredemmott** [comment]
@jamesgpearce : how about without the extra args, and how do the stats (especially byte size and 200 rate compared to the other response codes) compare to without this diff?

**Comment by rrh** [comment]
Yes, I understand that.  Our internal solution for problems like this has been to cache all of the 3rd party stuff on a local ftp server, but that won't really work in this situation, I agree.  I withdraw my suggestion :)

**Comment by jamesgpearce** [comment]
{
    "Combined": {
        "Siege requests": 32753,
        "Siege wall sec": 0.36,
        "Siege RPS": 548.35,
        "Siege successful requests": 31153,
        "Siege failed requests": 0,
        "Nginx hits": 32953,
        "Nginx avg bytes": 29399.132734501,
        "Nginx avg time": 0.36017628137044,
        "Nginx P50 time": 0.351,
        "Nginx P90 time": 0.455,
        "Nginx P95 time": 0.492,
        "Nginx P99 time": 0.768,
        "Nginx 200": 29790,
        "Nginx 499": 163,
        "Nginx 301": 1400,
        "Nginx 404": 1600,
        "canonical": 1
    }
}

VS

{
    "Combined": {
        "Siege requests": 36931,
        "Siege wall sec": 0.32,
        "Siege RPS": 616.44,
        "Siege successful requests": 35331,
        "Siege failed requests": 0,
        "Nginx hits": 37131,
        "Nginx avg bytes": 30952.137566993,
        "Nginx avg time": 0.32134693382888,
        "Nginx P50 time": 0.318,
        "Nginx P90 time": 0.409,
        "Nginx P95 time": 0.439,
        "Nginx P99 time": 0.508,
        "Nginx 200": 33775,
        "Nginx 499": 156,
        "Nginx 301": 1600,
        "Nginx 404": 1600,
        "canonical": 1
    }
}

Bear in mind there's a different theme so the bytes are different. Interestingly it seems a little faster. But close enough to prove it's working.

**Comment by jamesgpearce** [comment]
Interesting that there are more 301s. Thoughts?

**Comment by fredemmott** [comment]
Looks close enough given in the overall request increase, and near-constant average bytes. Please rebase.

**Pull request merged**
