### PR TITLE
hhvm.server.implicit_flush=1

### PR DESCRIPTION
**Pull request by reedy**

### CODE REVIEW

**Comment by reedy** [comment]
Not sure if this would actually be wanted..

**Comment by fredemmott** [comment]
I'd rather keep the config minimal - as we're not hitting error pages (hopefully), this isn't relevant to perf

**Comment by reedy** [comment]
That was the only way of getting useful debugging (including error messages) to find why HTTP 500 were being served by MW 1.26.0 using oss-performance without running hhvm seperately to run mw...

https://github.com/hhvm/oss-performance/pull/57#issuecomment-160369360 and as such https://github.com/facebook/hhvm/issues/5834 and https://github.com/facebook/hhvm/issues/5833

**Comment by octmoraru** [comment]
Having this option on exposes A LOT of socket write errors, especially for the WP benchmark. These are the types of errors we see in the logs:

```
HPHP transport error: what="Write on transaction id: 1. writev failed (peer=<uninitialized address>, local=<uninitialized address>): errno = 104", direction=2, proxygenError=Write, codecStatusCode=-1, httpStatusCode=0
HPHP transport error: what="Write on transaction id: 1. writev failed (peer=<uninitialized address>, local=<uninitialized address>): errno = 32", direction=2, proxygenError=Write, codecStatusCode=-1, httpStatusCode=0
```
If I read this correctly, some of the connections seem to be unexpectedly closed by the client (104 is ECONNRESET and 32 is EPIPE).
So the errors themselves seem benign but having HHVM log them causes a lot of siege sockets to time out and the reported performance to be severely impacted.

```
[alert] socket: -680433920 select timed out: Connection timed out
[alert] socket: -974178560 select timed out: Connection timed out
[alert] socket: -1343457536 select timed out: Connection timed out
```
IMHO logging these while running the benchmark does not bring much value. It's definitely useful for debugging and should be activated only for this purpose.

**Comment by fredemmott** [comment]
Thanks :(

**Comment by reedy** [comment]
Is it worth leaving in a commented state, with a comment next to it saying for debugging purposes?

**Pull request merged**
