### PR TITLE
Update siege blacklist to 3.0

### PR DESCRIPTION
**Pull request by reedy**
refs https://github.com/hhvm/oss-performance/issues/50

### CODE REVIEW

**Comment by fredemmott** [comment]
Sorry for the delay; I'm no longer working on HHVM, and have asked for a new internal volunteer to take over this project - if that doesn't happen, I will get to this, but it might take a while.

**Comment by mofarrell** [comment]
Somehow this is already in master.

**Comment by reedy** [comment]
No it didn't?

Patch changes 3 to 3.0, and updates the error message... Master hasn't changed in 2 years https://github.com/hhvm/oss-performance/blame/master/base/Siege.php#L31

**Comment by mofarrell** [comment]
Whoops.  I think I have patched this locally.

**Comment by reedy** [comment]
Hahahaah. Thanks! 👍

**Pull request merged**
