### PR TITLE
Adding a command line option to specify a remote Siege client.

### PR DESCRIPTION
**Pull request by kevand900**
Please note you must set up privileged SSH connection between the Server and Client.
It is also necessary to modify IP tables to allow INPUT and OUTPUT between Server and Client.
Remote Client is specified by --remote-siege=user@host, and is to be paried with --i-am-not-benchmarking.

### CODE REVIEW

**Comment by kevand900** [comment]
Can someone please review? Thanks!

**Comment by mofarrell** [comment]
@kevand900 This seems okay, but I don't know why it would be useful.

**Comment by kevand900** [comment]
Having the Siege client able to run on a separate machine better represents a real-world scenario, as well as freeing up cycles for HHVM to be fully exercised.

**Comment by mofarrell** [comment]
Have you done any experiments showing that the results aren't extremely noisy?  I have had concerns with a lot of the recent changes moving things off the box.  Yes is it more realistic in that your requests will be coming from else where, but it also means you might be measuring bottlenecks other than the webserver performance, and degrade the reproducibility of results.

**Comment by gdbentley** [comment]
@mofarrell We're aware of the potential pitfalls. The intention is to perform measurements on an isolated high-speed subnet. If you'd like, we can schedule a meeting to discuss what we have in mind.

**Pull request merged**
