### PR TITLE
Fixed check for gzcat (and made it quieter).

### PR DESCRIPTION
**Pull request by gdbentley**

### CODE REVIEW

**Comment by fredemmott** [comment]
What platform? cc @jwatzman

I wouldn't be surprised if this check is non-portable

**Comment by gdbentley** [comment]
It was failing for me on CentOS 7. I have a zcat but no gzcat. $cat ended up an empty string.

**Comment by jwatzman** [comment]
The `2>/dev/null` is fine, but can we make the `if` test just check for `!$cat`? It wouldn't surprise me if we got different results (null vs empty string) on different platforms.

**Comment by gdbentley** [comment]
!$cat works for me.

**Pull request merged**
